# Generated by Django 2.2 on 2019-05-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AddField(
            model_name='post',
            name='show_in_footer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='show_in_sample',
            field=models.BooleanField(default=False),
        ),
    ]
