# Generated by Django 2.2 on 2019-05-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20190504_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Unknown', max_length=120),
            preserve_default=False,
        ),
    ]
