# Generated by Django 2.2 on 2019-05-05 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190501_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 5, 5, 16, 23, 20, 382194, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
