# Generated by Django 2.2 on 2019-05-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bloguser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='date_joined',
        ),
    ]
