# Generated by Django 2.2 on 2019-05-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_bloguser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='email',
        ),
    ]
